# Generated by Django 4.2.1 on 2023-05-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_movie_movieinstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieinstance',
            options={'ordering': ['fecha_visualizacion']},
        ),
        migrations.RenameField(
            model_name='movieinstance',
            old_name='due_back',
            new_name='fecha_visualizacion',
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(help_text='Reseña de la pelicula', max_length=2500),
        ),
    ]
